[GOOGLE_CREDS]
type = "service_account"
project_id = "stockcountapp-465915"
private_key_id = "3cba0dca9b6b9163caa1c8a9e4f29bbddc0cdb37"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCk0CLwJAf0/UvY
pj2VPzJ9xJ07NBh/C7s+0SJZA6BF0tgUAO0MCQFPNL+mdAJivVnSlIJ/Wen49RLK
f7a6yLjEKZ7wpoaC8BeetLlaXWKaLtXNbOOQiJJ4Zm7mh1UFNM4tsdeZErcjx3f5
BgclamjdF/rzf6oK/L2XHsIAyFAoazXvYyss0RGYU4BPEoCTV6LioFPkIx1jc+xB
offhyTCUNX4zUO9+ZcdGLKAqEjYECvUv3LMT7182VYtoLrdTWx1Qeqlx4VToH08f
TmcVY8jdokpfa9MqBxG2P9YK3OweNk11YjPprUCIvDmRPjlqGzBPYC23JhwwAGvH
G0lx9M/pAgMBAAECggEAAxgvV7/tcFGjL22roVY+7fKXmyl2vkfrm5nUocQ6KaV0
TifYS44Nur18TbVG6DCy84u7SYXYKUb8s9WjCi3DnldDtzQBOYslfmLZShOPyuJP
PFyrhyaxTVZrBaQL2h2sM1pv+F1MF/1iSMgusSqmzmPpX9IJUMx/CMvYi6g3LRMS
iO+jp9tPSAt5f6iMmPg+zfm86/eFkqSPq6D9Y/W34R3CoeBNYgxZjkJAmLH1ebBG
u9HHYHPvakWKSITUvim6fCGJFaS0KRqXKc4vTGcSZACTBCfMV4R/h/qG8VsxNf9G
bBgIi7VFEchyvIPQ6BFG1Z7AK5StSTAPE1FhSr7wAQKBgQDPfaIuFvaHayb81Tui
BwU+vkDRxk0/eQpuO147zXbiGY6JDGM7o+eUKai/GatrVYpHCjf01v/OpGQgxvZi
EY/sxe1M2dyTLOuVU4zXclK1N8btbJci7rxeNUA/1umjW33In1raA5kysg/bPIKC
xQiAAZ8uFHqz3ARKPEZ2ph3T6QKBgQDLWDtngGFTEx1r1ckVx8Bj41mZr+UmYqJu
fEwNb4bfGuwUvyCeqfhM/Y5qYpFn1FCIrc6E+jE7BTWk3scaEb29atIuDvXsG8l2
g83QbMs3apI7MogGMVbB98e+LAQ52JGG8ZqeS6SWg3ORafFn0d5iuWZVl+IMFoor
3b8p8O2cAQKBgQC8jtpkch/Ffp3mpEzV+PVOSI0VVdV7eh79f9wqEpUX8cuzRduk
JlZcMeOVDtnV592Ko4Gocf30JzaLBuR+yKD3tgLplQ67fNX2VQAoBk+dObwApW9P
oo7yOghSO5cFCi7rs81XVG/TPzfjr0CXYEFSOqcStC+x5Z7Ma6xJRLrUiQKBgGkx
QLHfYPmn5s11L+w7hJRn9V8i9kkwN1Uuqe09Z6kc9UoaQZay2QeDF9yDFzN+SxcZ
yr9R6ovcuw6KTLd4vA40J3y6MpAtI8BSmPMchNgrInDLSEDj3zzCoKsJfDoshcQo
UlNXUFKot+1ewAp0MDYkMQNQahjUxC/DK/RXdaQBAoGBAJ1tyvHAqgExaQg/thwT
hz3BhV3cdi5x9SDzvnZwLGDjssTVTkSJh9lc0WQLvkZP+LlrvMJG70UIFkngcIDo
QSwsx2BXaQj2EMuOfm8jR1ggH1L5yyJpi5IA7v2bE4nsNny92O2Eo/BRyOlIFvOg
ss9bWANSsjXcORps9klZdVza
-----END PRIVATE KEY-----
"""
client_email = "inventory-access-sa@stockcountapp-465915.iam.gserviceaccount.com"
client_id = "117833808872184162568"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inventory-access-sa%40stockcountapp-465915.iam.gserviceaccount.com"
universe_domain = "googleapis.com"