[GOOGLE_CREDS]
type = "service_account"
project_id = "stockcountapp-465915"
private_key_id = "18d984820f6d883e95b7f08df89e421d0ffec42b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCQ+4vR+FmPIAPk
pkZWVXKIfHbawxEk5g2wqikpjBmm0axvDq7ICQjFYjnT0vJCaFlMOHTa8RT25CWV
... (rest of your private key lines here) ...
-----END PRIVATE KEY-----"""
client_email = "inventory-access-sa@stockcountapp-465915.iam.gserviceaccount.com"
client_id = "117833808872184162568"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inventory-access-sa%40stockcountapp-465915.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
